### ISSUE TITLE
Cannot find the stable_baselines3

### ISSUE THREAD

**Issue by arfff527** [RobbertReijnen/DR-ALNS#1]
<img width="464" alt="截屏2024-05-29 11 06 02" src="https://github.com/RobbertReijnen/DR-ALNS/assets/159047836/463d4dc7-6795-4bb4-b0e3-4928b50a6c70">
Hello, Robbert, When I try run the code, seems no stable_baselines3 package or file.

**Comment by RobbertReijnen** [comment]
Hi there, nice that you are trying to setup my repo. I have worked on this project using python 3.10, and it should also work for python 3.11. Have you tried setting up a virtual environment, and tried pip install -r requirements.txt ?

You could also try: pip install stable-baselines3[extra] or pip install stable-baselines3 

Let me know if this works.

Best,
Robbert

**Comment by arfff527** [comment]
Thanks Robbert, the probelm has been solved.
